### ISSUE TITLE
Doesn't work for me 

### ISSUE THREAD

**Issue by ThePlatinumGhost** [jusito/ttt_entity_replace#1]
![image](https://user-images.githubusercontent.com/36534723/81169479-33cc0b80-8f99-11ea-9f26-e5b16ff6ccbe.png)
keep spamming this error and also for strange reason deleted player spawn
this is my config.txt file 
![image](https://user-images.githubusercontent.com/36534723/81169699-902f2b00-8f99-11ea-86a5-8146d28a62a2.png)
can you help me?

**Comment by jusito** [comment]
It looks like you have to many entities, even before the spawn is created.
I don't think this is only the problem of this mod, because the game spawns any ent first and after its creation I handle it, if the server is slow and the client fast you can see it. According to your log, the spawn isn't created because there is already to much of other stuff, so the script at least didn't directly remove the spawn, the spawn is never spawned.

It could be that the script or a mix of mods replacing stuff from above and duplicating something.
Do you have any mod which is adjusting the rate of ents? E.g. 30% more weapons or ammo?
Because for this it would need to hook into creation, i get notified spawning random ammo / weapon which may trigger the other mod, which triggers this mod aso.

If you place the script by hand you can change the variable for debugging to true, the complete server.log would be nice with it. Line 3:
https://github.com/jusito/ttt_entity_replace/blob/master/lua/autorun/server/jusito_ttt_entity_replace.lua#L3

info_player_deathmatch is the spawn:
https://developer.valvesoftware.com/wiki/Info_player_deathmatch

On every ent creation this function is called directly:
https://github.com/jusito/ttt_entity_replace/blob/master/lua/autorun/server/jusito_ttt_entity_replace.lua#L426-L447

**Comment by ThePlatinumGhost** [comment]
You can check my collection https://steamcommunity.com/sharedfiles/filedetails/?id=1806066645

the only thing that i think can be maybe this ?
https://steamcommunity.com/sharedfiles/filedetails/?id=1741790902

anyway i use ttt weapon placer for add o edit weapon and spawn in the maps

if you have any advice that can resolve the problem, you are more than welcome

i will send you the server.log tomorrow!

**Comment by ThePlatinumGhost** [comment]
sorry I can't understand where I can find the server.log is it a file? where can I find it?
I only find "clientside_errors.txt" which I don't think is what interests you

**Comment by jusito** [comment]
The logs are default in garrsymod/logs folder with ".log" extension, server variables for it:
https://forums.alliedmods.net/showthread.php?t=170556
Maybe you disabled log to file and thats why you can't find it.

**Comment by ThePlatinumGhost** [comment]
I followed the guide you linked to me I don't know if this is what you are interested in
log "1"
sv_log_onefile "0"
sv_logflush "1"
sv_logbans "0"
sv_logecho "1"
sv_logsdir "logs"
sv_logfile "1"
sv_rcon_log "1"
mp_logdetail "1"

con_logfile "my_file.txt"
con_timestamp "1"

this is the file [L0510001.log](https://github.com/jusito/ttt_entity_replace/files/4606807/L0510001.log)

if I did something wrong, tell me

**Comment by jusito** [comment]
Correct log, but doesn't contain all error messages from image.
It looks like maps/ttt_rooftops_2016_v1_ttt.txt throws a lot of lua errors. Looks like a file from weapon placer: http://ns551503.ip-142-44-143.net/fastdl/Admin/4/garrysmod/maps/ttt_rooftops_2016_v1_ttt.txt
1. The mod with random ammo boxed shouldn't be a reason for this problem, but ofc to be completly sure disable it and try again.
2. Please execute jusito_weapons_list in rcon / console and put it in a text file here. The command will list all weapons / ammo which can be spawned. Because if iam right, you have no other weapons as the default ones. In the script above you replacing every normal weapon with a random weapon, random weapons are (without mods) the normal weapons. This would mean an endless loop, do you have any non-traitor / non-detective / ..  weapons added which spawns naturally without my script? If iam wrong iam suggesting to replace ttt_random_ammo with the correct class names from jusito_weapons_list. This are the same class names you get from: https://steamcommunity.com/sharedfiles/filedetails/?id=933160196
3. Can you test if the errors occure without _maps/ttt_rooftops_2016_v1_ttt.txt_?

**Comment by ThePlatinumGhost** [comment]
the major problem is with random ammo, the change is only applied to weapon, the ammo do not spawn
1) I tried without and didn't change nothing, same issue

3) I finally figured out how to find the information you wanted was enough to write "-condebug" in the start.bat
here is the file you are interested in I also wrote the command you requested "jusito_weapons_list"
[console.log](https://github.com/jusito/ttt_entity_replace/files/4616785/console.log)
I have m9k weapon as non-traitor/non-detective randomspawn
you can find it in my collection https://steamcommunity.com/sharedfiles/filedetails/?id=1806066645


2)  Without maps/ttt_rooftops_2016_v1_ttt.txt same issue

**Comment by jusito** [comment]
Ok thanks:
Its looking like the loop I expected:
1. default weapons are spawned
2. your mapping tells replace it with ttt_random_*
3. game processing ttt_random and choosing a default weapon, redo at 1.

But even with the loop, it shouldn't consume all entity ids, maybe I need to call another method to remove them and free the id, but this wouldn't resolve this issue - but I should look into it. I think the problem is that the m9k_* arent spawned with ttt_random_*, from a quick view they should because "spawnable" (issue with other mods or the mod itself or gmod).

I would suggest to map them directly like I did with fas2:
[config.txt](https://github.com/jusito/ttt_entity_replace/files/4617367/config.txt)

Because there will be a lot of random ammo you can't use with your weapon of choice, you could check if there is an item like fas2 ammobox which gives ammo to every weapon and just reduce drop rate.
e.g. replace every given ammo in 25% with ammobox, 75% just delete it (becausen nothing is no valid classname)
```
source
	ammo1
	ammo2
target
	ammobox
	nothing
	nothing
	nothing
end
```

Edit: Tested it myself the config.txt from above is working with your collection.
From what I know I have todo after this:
1. why are ent ids consumed even if removed
2. ammo isn't listed with justio_list_weapons (maybe another ammo command needed)
3. add command to list only spawnable/autospawnable weapons
4. Update readme, what do you think you would missed from readme for this resolve?
And btw seems like the m9k weapons are better as fas2, at least the scopes.

**Comment by ThePlatinumGhost** [comment]
I have seen your config.txt and the problem is that I would like them to spawn the normal ammo also because the m9k also work with those and are more balanced (m9k_ammo give like 1000 bullets) so i don't like this part
![image](https://user-images.githubusercontent.com/36534723/81732499-e0722580-9490-11ea-92e1-b89a49c74d1b.png)
if I remove this part and leave it empty should it work the same or i need to do this?
I would like something more like this 

![image](https://user-images.githubusercontent.com/36534723/81733310-16fc7000-9492-11ea-820b-842c34673ab3.png)

**Comment by ThePlatinumGhost** [comment]
ok i simply removed the part and i think it works

**Comment by jusito** [comment]
Not every map using ttt_random_ammo and if you are placing it by hand, i assume its the specific ammo type also. Just in case its direct spawned, I would use this. But this would remove every occurence.
```
# replace ammo
source
	ttt_random_ammo
	m9k_ammo_357
	m9k_ammo_ar2
	m9k_ammo_buckshot
	m9k_ammo_pistol
	m9k_ammo_smg
	m9k_ammo_sniper_rounds
	m9k_ammo_winchester
target
	item_ammo_pistol_ttt
	item_ammo_revolver_ttt
	item_ammo_smg1_ttt
	item_ammo_357_ttt
	item_box_buckshot_ttt
end
```

**Comment by ThePlatinumGhost** [comment]
Thanks for your assistance, if I encounter other problems or anything else, I will tell you
